INSERT INTO public.product (productname,imagepath,salesprice,categoryid,description,longdescription,trendyproduct,status) VALUES
	 ('Philips 12''li 8 W - 60 W Beyaz Işık LED Ampul','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663454147/product_picture/ev-ya%C5%9Fam/4-min_ktrzcv.webp',166.00,3,'Philips 12''li 8W Beyaz Işık 6500 kelvinLED Ampul','* Işık Çıkışı: 806 Lümen',0,0),
	 ('Technosmart Hareket Sensörlü Güneş Enerjili Şarj Olabilen 20 Ledl','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663454147/product_picture/ev-ya%C5%9Fam/3-min_e6bpak.webp',89.95,3,'Hareket Sensörlü Solar Güneş Enerjisi ile şarj olabilen 20 ledli Bahçe Lambası','Bahçenizde , Villanızda , Verandanızda kullanabileceğiniz bir üründür. Güneş Enerjisi depolayarak çalıştığı için Tasarruf sağlayacağınız görünümü çok şık ve kaliteli bir üründür.',0,0),
	 ('Azrayatakmobilya Tek Kişilik Yatak+Baza + Başlık Basic 90 x 190 CM','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663454147/product_picture/ev-ya%C5%9Fam/2-min_grvflt.webp',2099.00,3,'Azrayatakmobilya Tek Kişilik Yatak+Baza + Başlık Basic 90 x 190 CM','Kendinden Stop lu 1500 newton Özel Amortisörler',0,0),
	 ('Relaxion 2023 Siyah Su Geçirmez Astarlı Kumaş Sırt Çanta','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663454147/product_picture/ev-ya%C5%9Fam/1-min_ejrsms.webp',363.10,3,'Relaxion 2023 Siyah Su Geçirmez Astarlı Kumaş Sırt Çanta','Relaxion Sırt Çantası 2023 Siyah',0,0),
	 ('Reeder P13 Blue Max Pro 256 GB (Reeder Türkiye Garantili)','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663454567/product_picture/elektronik/1-min_hrieum.webp',2909.03,2,'Reeder P13 Blue Max Pro 256 GB (Reeder Türkiye Garantili)','Ürünler; 2 yıl REEDER TÜRKİYE garantilidir.',0,0),
	 ('LG OLED55C14LB 55" 4K Ultra HD Smart OLED TV','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663454568/product_picture/elektronik/2-min_uxuv6k.webp',28649.05,2,'LG OLED55C14LB 55" 4K Ultra HD Smart OLED TV','4K çözünürlük yapı özelliğine sahip olup canlı renk ve yüksek kalite performans özelliğiyle dikkat çeker. Dinamik hareket senkronizasyon özelliğine sahip olup gecikme problemlerini en az seviyeye indirerek tüm film, dizi ve oyunlarınızı hızlı ve güvenli bir şekilde ekrana yansıtır.',0,0),
	 ('Seagate STEA500400 Expansion 500 GB 2.5" USB 3.0 Taşınabilir Disk','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663454568/product_picture/elektronik/3-min_d62wiv.webp',398.99,2,'Seagate STEA500400 Expansion 500 GB 2.5” Usb 3.0 Taşınabilir Disk','Bilgisayar performansını önemseyenler, gereksiz dosyalarla bilgisayarında kalabalık oluşmasını istemeyenler için 500 Gb ideal kapasitesiyle harici bir alan sunar. Fotoğraf, müzik, video gibi yer kaplayıcı ve bilgisayar hafızasını yoran dijital dosyalarınızı hızlıca aktarabilirsiniz. Ayrıca önemsediğiniz ve ihtiyaç duyduğunuz dosyaları transfer edebilir, ihtiyaç anında kolayca ulaşım sağlayabilirsiniz.',0,0),
	 ('Kallow Z10 Sim Kart Özellikli Akıllı Çocuk Takip Saati','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663454568/product_picture/elektronik/4-min_l5noqg.webp',329,2,'Kallow Z10 GPS Sim Kartlı Akıllı Çocuk Saati (İthalatçı Garantili)','Ders Modu: Çocuğunuz okulda ise rahatsız edilmesini veya Saat ile meşgul olmasını istemiyorsanız ders modunu seçebilirsiniz.',0,0),
	 ('Maxi-Cosi Milofix 0-18 KG Oto Koltuğu','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663455852/product_picture/anne-bebek/2-min_bsn14x.webp',2399.50,4,'Maxi-Cosi Milofix 0-18 KG Oto Koltuğu','axi-Cosi, bebeğinizin doğumundan 13 kilogram olana kadar arkaya dönük bir biçimde kullanılırken 9-18 kilogram arasına geldiğinde öne dönük biçimde kullanıma uygun olabilir. Optimum güvenlik sağlayan dizaynıyla yan darbe korumalarına karşı dayanıklı bir yapı sunabilir. Tek hareketle çekilen ve kolayca bağlanabilen 5 noktalı emniyet kemer sistemiyle bebeğinize güvende tutabilir. Isofix bağlantısıyla oto koltuğu, arabanıza daha güvenli bir biçimde sabitlenir. Yeni doğan bebeklerinize yastık gibi rahat bir oturma alanı sağlar.',0,0),
	 ('Uni Baby Aktif Bebek Islak Havlu Mendil 24 x 72''li','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663455852/product_picture/anne-bebek/3-min_fzjgq8.webp',325,4,'Uni Baby Aktif Bebek Islak Havlu Mendil 24 x 72''li','Uni Baby Aktif Bebek Islak Havlu Mendil 24 x 72''li',0,0);
INSERT INTO public.product (productname,imagepath,salesprice,categoryid,description,longdescription,trendyproduct,status) VALUES
	 ('Dynamic A300 Aero 2 HP AV Motorlu Katlanabilen Koşu Bandı','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663456241/product_picture/spor/1-min_lqs1tg.webp',5814,5,'Dynamic A300 Aero 2 HP AV Motorlu Katlanabilen Koşu Bandı','Çok daha sağlıklı yaşamak isteyenler ve sporunu hiçbir zaman ihmal etmek istemeyenler için tasarlanmış olan bu özel ürün, geniş yürüme alanı, ayarlanabilen eğim ayarı, kolay kullanım sunan ekran paneli ile birlikte spor yapmak isteyen herkesin rahatlıkla spor yapmasını mümkün hale getiriyor.',0,0),
	 ('Onetick 4 Kişilik Renkli Dayanıklı Kamp Çadırı 200 x 200 x 135 CM','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663456240/product_picture/spor/2-min_xamdkv.webp',296.91,5,'Onetick 4 Kişilik Renkli Dayanıklı Kamp Çadırı 200 x 200 x 135 CM','Kolay Kurulum',0,0),
	 ('Ronic Nutrition Whey Ultimate 2270 Gr 2 Hediyeli Protein Tozu','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663456241/product_picture/spor/3-min_nybcgb.webp',559,5,'Ronic Nutrition Whey Ultimate 2270 Gr 2 Hediyeli Protein Tozu','Ultimate Whey Protein Tozu 2270 G + Shaker ve 2 Adet Tek Kullanımlık Whey Protein Hediye - 1772',0,0),
	 ('Nivea Sun Koruma & Nem Güneş Spreyi Spf 50 200 ML','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663456802/product_picture/kozmetik/1-min_wfdv59.webp',168.98,7,'Nivea Sun Koruma & Nem Güneş Spreyi Spf 50+ 200 ML','Nivea Sun Koruma & Nem Güneş Spreyi Spf 50+ 200 ML',0,0),
	 ('Avon Wish of Love Kadın Parfüm EDT 50 ML','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663456802/product_picture/kozmetik/2-min_bnndq7.webp',49.72,7,'Avon Wish of Love Kadın Parfüm EDT 50 ML','Baharın habercisi Avon Wish of Love hassas , taze , meyvemsi notaları ile tatlı çiçek esansları sayesinde romantik bir esinti hissi vermektedir. Wish of Love 2008 yılında pazara çıktı. Kızılcık anlaşması yanında çevrili gül yaprakları , kiraz çiçeği ve pembe ortancalar içeriğindeki elementlerdir. Bu narin ve kadınsı parfüm günlük kullanım için idealdir. Wish of Love Avon Wish koleksiyonunun bir parçasıdır.',0,0),
	 ('Land Of Myth 1x ve 5x Büyütmeli 23 Led Işıklı Makyaj Aynası','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663456802/product_picture/kozmetik/3-min_zi4quj.webp',282.96,7,'Land Of Myth 1x ve 5x Büyütmeli 23 Led Işıklı Makyaj Aynası','Yeni nesil LAND OF MYTH LOM2021 makyaj aynası, diğer geleneksel makyaj aynası modellerinde bulunan ayna çerçevesindeki standart açma kapama düğmesi yerine cam ayna ekranı üzerinde bulunan dokunmatik bir akıllı sensöre sahiptir. Bu dokunmatik sensör ile led ışıkları açıp kapatabileceğiniz gibi, tuşa kısa bir süre basılı tutarak ışık miktarını artırıp azaltabilirsiniz (Stepless Dimming). Düşük ışık veya gözlerinizi kamaştırabilecek yüksek ışık arasında sizin için en uygun olan ışık miktarını ayarlayabilirsiniz.',0,0),
	 ('Powertec TR-1818 Sakal Ense Çizim Makinesi','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663457128/product_picture/bak%C4%B1m/1-min_t3khic.webp',257.93,10,'Powertec TR-1818 Sakal Ense Çizim Makinesi','Şarj edilerek kullanılan bu sakal ense çizim makinesini isterseniz kablo ile isterseniz de şarj ederek kullanabileceksiniz. 4,5 saat gibi kısa bir sürede şarj olan sakal ense çizim makinesi şarj olduktan sonra 180 dakika boyunca kesintisiz olarak kullanılabilecektir. Bu kablosuz kullanma imkânı sayesinde çok kolay ve özgür şekilde kullanabilirsiniz.',0,0),
	 ('Medinail Tırnak Bakım Spreyi 100 ML','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663457128/product_picture/bak%C4%B1m/2-min_nsfckx.webp',139,10,'Medinail Tırnak Bakım Spreyi 100 ML','Medinail Tırnak Bakım Spreyi 100 ML',0,0),
	 ('Opalescence Cool Mint Beyazlatıcı Diş Macunu 133 G','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663457128/product_picture/bak%C4%B1m/3-min_sixvrb.webp',157.41,10,'Opalescence Cool Mint Beyazlatıcı Diş Macunu 133 G','Diş eti iltihabı başta olmak üzere, diş eti hastalıklarına sahip kişiler tarafından gönül rahatlığıyla tercih edilebilir. Diş eti sağlığına olumlu destek olur. Nazikçe dişlerin beyazlatılmasını sağlar.',0,0),
	 ('Lacivert Regular Fit %100 Pamuk Polo Yaka Tişört','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663457494/product_picture/bahar/1-min_w7bewf.webp',169.90,11,'Lacivert Regular Fit %100 Pamuk Polo Yaka Tişört','Lacivert Regular Fit %100 Pamuk Polo Yaka Tişört',0,0);
INSERT INTO public.product (productname,imagepath,salesprice,categoryid,description,longdescription,trendyproduct,status) VALUES
	 ('Mavi - Miav Baskılı Beyaz Tişört 1610622-620','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663457494/product_picture/bahar/2-min_y21jso.webp',129.99,11,'Mavi - Miav Baskılı Beyaz Tişört 1610622-620','Mavi - Miav Baskılı Beyaz Tişört 1610622-620',0,0),
	 ('NBB Kadın Lacivert Kapüşonlu Şort Takımı','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663457494/product_picture/bahar/3-min_nov1wc.webp',135.94,11,'NBB Kadın Lacivert Kapüşonlu Şort Takımı','NBB Kadın Lacivert Kapüşonlu Şort Takımı',0,0),
	 ('Umut Hakiki Deri Tam Ortopedik Erkek Ayakkabı','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663458155/product_picture/moda/1-min_qb6v5r.webp',384.99,1,'Umut Hakiki Deri Tam Ortopedik Erkek Ayakkabı','%100 İÇİ DIŞI DERİ TAM ORTOPEDİK RAHAT YUMUŞAK ERKEK AYAKKABI',0,0),
	 ('Önden Cepli Gabardin Etek - Camel','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663458155/product_picture/moda/2-min_woyidh.webp',59.88,1,'Kadın - Önden Cepli Gabardin Etek - Camel','Modelin Ölçüleri: Boy: 176 m, Kilo: 55, Göğüs: 87, Bel: 63, Basen: 93 Modelin Üzerindeki Ürün S Bedendir. Kumaş Türü : Gabardin Ürün Boyu: 55 cm Ürünlerimiz Tam Kalıptır. Günlük Hayatta Kullandığınız Bedeni Satın Almanız Tavsiye Edilir. Yıkama Talimatı: 30 dereceye kadar hassas veya kırışık azaltma döngüsü ve sentetik döngüsünde yıkayınız. Ürün ağartıcı ile yıkanmamalıdır sadece renkli ve hafif deterjan kullanılmalıdır. Konsept Çekimlerinde Renkler Işık Farklılığından Dolayı Değişiklik Gösterebilir.',0,0),
	 ('Anemoss Çapa Şal','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663458155/product_picture/moda/3-min_dk5tyd.webp',159.90,1,'%100 Pamukludur. Ölçüler: Boy: 90 cm / En 1.70 cm. ','Gamze Yalçın''ın Çapa eserini uyuglandığı şal. Pamuklu yapısı sayesinde kırışmaya dayanıklı ve nefes alıcı özelliğe sahiptir. İnce dokusuyla rahat bir kullanım sağlar. Bahar aylarında rahatlıkla kullanabileceğiniz bu şal kombinlerinizin tamamlayıcı parçası olacak. Desen dijital baskı yapılarak uygulanmıştır. Lacivert ve beyaz renklidir.',0,0),
	 ('Buratti Erkek Mont 5711051','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663457848/product_picture/k%C4%B1%C5%9F/1-min_ahlali.webp',649.99,12,'Buratti Erkek Mont 5711051','Buratti Erkek Mont 5711051',0,0),
	 ('Never More Kemer Detay Kürklü Mont','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663457848/product_picture/k%C4%B1%C5%9F/2-min_aimgat.webp',1599,12,'Never More Kemer Detay Kürklü Mont','%100 Süet Manken Ölçüleri: Boy: 178 cm Göğüs: 80 cm Bel: 58 cm Kalça: 82 cm Kilo:51 · Ürün Boy:70 · Kol:60 · Bel:50 · Menşei:Türkiye',0,0),
	 ('İkbal Larissa Taba Hakiki Deri Mont Kadın','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663457848/product_picture/k%C4%B1%C5%9F/3-min_ej4d85.webp',2269.99,12,'Model ölçüleri: Boy:1,79 Göğüs:86 Bel:64 Kalça:94','Ürünlerimiz %100 orijinal deri ve adınıza faturalı olarak gönderilmektedir. Ürünlerimiz özel kalın karton kutular ile gönderilmektedir. Bu sayede ürün size taşıma süresince hiç bir zarar görmemiş olarak teslim edilecektir. Tüm siparişleriniz azami süre içerisinde kargoya teslim edilecektir.',0,0),
	 ('Pirelli 215/45 R17 91W XL Cinturato P7 Yaz Lastik 2021','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663458436/product_picture/otomotiv/1-min_wvllrj.webp',1911.99,6,'Pirelli 215/45 R17 91W XL Cinturato P7 Yaz Lastik 2021','Pirelli 215/45 R17 91W XL Cinturato P7 Yaz Lastik 2021',0,0),
	 ('4 Mevsim Ekstra Koruma Pedli Motosiklet Montu','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663458436/product_picture/otomotiv/2-min_p0u57d.webp',929.99,6,'4 Mevsim Ekstra Koruma Pedli Motosiklet Montu','İÇLİK ASTARI SÖKTÜĞÜNÜZDE MEMBRANLI İÇ ASTARDA ÇIKARILMIŞ OLUR FİLE ASTAR KALIR.',0,0);
INSERT INTO public.product (productname,imagepath,salesprice,categoryid,description,longdescription,trendyproduct,status) VALUES
	 ('Turtle Wax Hibrid Hızlı Cila 750 ML','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663458436/product_picture/otomotiv/3-min_iyvuoe.webp',255,6,'Turtle Wax Hibrid Sprey Cila, sentetik ve doğal carnauba içeren özel hidrofobik formülü ile aracınızın kurulama süresini kısaltırken göz alıcı parlaklığı ile harika bir sonuç verir.','Tek adımda parlaklık ve koruyuculuk sağlar. Araç yıkandıktan sonra ıslakken uygulanır ve mikrofiber bez ile kurulama işlemi yapılır. Hibrid Teknoloji Koruyucu Bariyer, su lekelerinden, böcek kalıntılarından, kuş pisliklerinden, şehir kirliliğinde n oluşan kimyasal lekelerden aracınızı korumaya yardımcı olur.',0,0),
	 ('Cox Flt-tl25s Metalofon.','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663458668/product_picture/m%C3%BCzik/1-min_wqlxgr.webp',647.76,8,'Cox FLT-TL25S Metalofon','Cox FLT-TL25S Metalofon',0,0),
	 ('Jwin Mk-6145 61 Tuşlu 5 Oktav Org','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663458668/product_picture/m%C3%BCzik/2-min_iefnzg.webp',1499.05,8,'Jwin Mk-6145 61 Tuşlu 5 Oktav Org','Kaliteli malzeme yapısına sahip,piyano stili tuşlar, iyi derecede ses seviyesine sahip, doğru notaları ve akorları yapabileceğiniz,piyano eğitiminde tercih edilebilecek özelliklere sahiptir. ',0,0),
	 ('Puka Pk100 Maun Soprano Ukulele Askı.Kılıf ve Pena','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663458668/product_picture/m%C3%BCzik/3-min_mnp3dx.webp',519,8,'Puka Pk100 Maun Soprano Ukulele Askı.Kılıf ve Pena','Tüm teller sıfır ve naylon olduğundan belli bir esneme payı vardır .Birkaç gün akort edilip çalındıktan sonra teller yerine oturmaktadır.',0,0),
	 ('Valorant 8500 VP','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663458926/product_picture/film/1-min_mmzhyp.webp',567.42,9,'Siparişleriniz çalışma saatlerimiz içinde işleme alınmaktadır. Satın almış olduğunuz ürünler E-teslimat şeklinde gönderilir.','Ürünler dijital olup, pin bilgileri ve satın alma detayı email veya mesaj kutunuza düşücektir.',0,0),
	 ('Maya The Bee Movie - Arı Maya 3D Blu-Ray','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663458926/product_picture/film/2-min_czpco9.webp',14.99,9,'Maya The Bee Movie - Arı Maya 3D Blu-Ray','Meraklı Arı Maya ve Willy, Kraliçenin hain danışmanından kovanlarını kurtararak arılar ve e şek arıları arasındaki düşmanlığı sona erdirir. Dünyayla yeni tanışan Arı Maya bir kasırga gibidir ve kovanın kurallarına uymamaktadır.Bu kurallardan biri de çayır ötesinde yaşayan eşekarılarına asla güvenmemektir. Arı sütü çalındığında herkes eş ek arılarından şüphelenir ve Maya''nından bu işte parmağı olduğunu düşünürler. En iyi arkadaşı Willy dışında kimse onun masum olduğuna inanmaz.E şek arılarının kovanına doğru uzun ve olaylı yolculuktan sonra Maya ve Willy gerçek suçluyu keşfederler.',0,0),
	 ('Pek Yakında Blu-Ray','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663458926/product_picture/film/3-min_vv1d9g.webp',16.49,9,'Pek Yakında Blu-Ray','Eski bir figüran olan Zafer%27in kanunsuz işlerinden tövbe edip, ailesini ve hayatını geri kazanmak için 1970%27lerden beri çekilememiş fantastik bir film senaryosu olan "Şahikalar-Kötülüğün Sonu" isimli projeyi hayata geçirmeye çalışmasını anlatır.',0,0),
	 ('Baby Turco Softcare Aloe Vera Islak Bebek Havlusu 12 x 120 Adet','https://res.cloudinary.com/ibtbcm/image/upload/c_crop,h_440,w_440/v1663455852/product_picture/anne-bebek/1-min_qntwlm.webp',147.99,4,'Baby Turco Softcare Aloe Vera Islak Bebek Havlusu 12 x 120 Adet','Baby Turco Softcare Aloe Vera Islak Bebek Havlusu 12 x 120 Adet',1,0);
